title: six_point_two_eight
description: C++14＋ROSプログラミング・ガイド
name: OJIMA Ryoji
email: rojima1@gmail.com
url: https://tail-island.github.io/six_point_two_eight
github: tail-island
twitter_username: tail-island
markdown: redcarpet
redcarpet:
  extensions: ["footnotes"]
permalink: /:title
